# Generated by Django 5.0.6 on 2024-05-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventtario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House')], max_length=10)),
                ('image', models.ImageField(upload_to='activos/')),
            ],
        ),
    ]
